name: pandas_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.6
  - lxml=4.6.2
  - matplotlib=3.3.4
  - pandas=1.2.1
  - pyarrow=3.0.0
  - pytables=3.6.1
  - python=3.9.1
  - seaborn=0.11.1
  - sqlalchemy=1.3.22
  - scikit-learn=0.24.2
  - jedi=0.17.2
  - statsmodels=0.12.1

