name: pandas_tutorial
channels:
  - defaults
dependencies:
  - jupyterlab=0.35.3
  - matplotlib=3.0.2
  - numpy=1.15.4
  - pandas=0.23.4
  - python=3.7.2
  - seaborn=0.9.0
  - sqlalchemy=1.2.16
  - pyarrow=0.11.1